### ISSUE TITLE
dev or contribution guide?

### ISSUE THREAD

**Issue by ly525** [lugia-ysstech/lugia-mega#15]
您好，请问下，在根据 [README](https://github.com/lugia-ysstech/lugia-mega#%E5%BC%80%E5%8F%91)  安装相关依赖之后。

本地运行 ` yarn start` 之后，如何访问 正在 dev 的项目呢？

**Comment by zenjava** [comment]
默认是在localhost:3000端口

**Comment by ly525** [comment]
download 了 mater 分支的 zip 包，在本地解压，根据 readme 安装依赖之后，访问 3000 端口，提示不可访问。感觉有问题，请教下如何解决？

![image](https://user-images.githubusercontent.com/12668546/69931341-d91e1780-1501-11ea-8e3a-3a20adfe85ef.png)

![image](https://user-images.githubusercontent.com/12668546/69931351-e509d980-1501-11ea-860f-7c18450c8df8.png)
