### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by ly525** [lugia-ysstech/lugia-mega#16]
复现： 下载 mega，创建项目，安装依赖时间过长，于是手动进入项目，yarn install, yarn start 报错：

其中：
node -v: v12.13.0
yarn -v: 1.16.0
@lugia/lugiad-loader: 1.2.4-alpha.0
mega 为最新版本

```js
yarn run v1.16.0
warning ../../package.json: No license field
$ lugia-scripts start
env: node\r: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

请问在哪里有比较清晰的开发文档吗？感觉现在略微有些晕乎乎的，搞不太清楚 lugia  和 lugia-mega 在开发层面的关系

**Comment by ly525** [comment]
![image](https://user-images.githubusercontent.com/12668546/69205125-070b6f80-0b84-11ea-954a-22f9d8e130a2.png)

**Comment by wittech** [comment]
/bin/sh: lugia-scripts: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by zenjava** [comment]
请更新1.4.8就可以正常使用
