### ISSUE TITLE
Help菜单下链接对应的地址都是electron相关的，请调整为 lugia相关的

### ISSUE THREAD

**Issue by zxd090603** [lugia-ysstech/lugia-mega#22]
![image](https://user-images.githubusercontent.com/23147227/72404122-3c50ca00-378f-11ea-9ede-a48b13bd9b52.png)
Help菜单下链接对应的地址都是electron相关的，请调整为 lugia相关的

**Comment by zenjava** [comment]
感谢你的关注，以后可以把问题提到 https://github.com/lugia-ysstech/lugia/issues，谢谢！
